### ISSUE TITLE
"estimate_range" and "estimate_full_charge_range" entity values

### ISSUE THREAD

**Issue by ohaue** [leeyuentuen/polestar_api#87] opened 2024-01-10 16:21 UTC
Version 1.5.4

The entity "estimate_range" and the entity "estimate_full_charge_range" seems to always have the same value.
Looks to me as if the "estimate_full_charge_range" has the "estimate_range" value.

I don't know if this is a 1.5.4 issue. It used to be correct before.

**Comment by leeyuentuen** [comment] 2024-01-10 18:01
one is the actual estimate range, the other one is if you have fully charge your car.

so if you can drive 200km on 100%, this is your full charge range, but if you still have 20%,  you can only drive  40km on your current battery level

**Comment by ohaue** [comment] 2024-01-10 18:07
![image](https://github.com/leeyuentuen/polestar_api/assets/63210219/5d7f1d7b-2ff3-406c-ae35-937b753dad2a)

**Comment by leeyuentuen** [comment] 2024-01-10 18:10
![Screenshot_2024-01-10-19-09-48-52_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/polestar_api/assets/1487966/650147fa-dabb-48ee-8232-4526043f74dd)

**Comment by ohaue** [comment] 2024-01-10 18:18
OK - must be a failure on my Polestar end :-)

![image](https://github.com/leeyuentuen/polestar_api/assets/63210219/3028c9bc-8f6d-40bf-a695-19b7c4cd1aa7)
![image](https://github.com/leeyuentuen/polestar_api/assets/63210219/844d5564-a812-4cd9-a25c-640667824ef5)

**Comment by leeyuentuen** [comment] 2024-01-10 18:20
i'll take a look, maybe there is some wrong code or something

**Comment by Ottmar0815** [comment] 2024-01-10 19:55
Same issue here.

**Comment by leeyuentuen** [comment] 2024-01-10 21:24
The full range value is based on the normal range and calculated with the battery percentage

I can't reproduce this issue, but maybe try this beta maybe that should be the issue:
https://github.com/leeyuentuen/polestar_api/releases/tag/1.5.5

**Comment by ohaue** [comment] 2024-01-10 21:44
Works for me now in 1.5.5:
![image](https://github.com/leeyuentuen/polestar_api/assets/63210219/cf1a3634-cfe3-4db5-bc0c-550a9a4991ea)

**Comment by VdR1960** [comment] 2024-01-12 15:26
I can confirm this to be fixed with the 1.5.5. release.

**Comment by leeyuentuen** [comment] 2024-01-18 15:42
https://github.com/leeyuentuen/polestar_api/releases/tag/1.6.0

**Closed by leeyuentuen** 2024-01-18 15:42 UTC
Labels: ready for release, Testing
