### ISSUE TITLE
current_odometer error

### ISSUE THREAD

**Issue by Borales** [leeyuentuen/polestar_api#82] opened 2024-01-08 23:36 UTC
Using 1.5.0

```
current_odometer: Value 89186896 is higher than max value 1000000
00:33:59 – (WARNING) Polestar API (custom integration) - message first occurred at January 8, 2024 at 17:15:32 and shows up 1755 times
```

**Comment by Borales** [comment] 2024-01-08 23:39
After several updates (on beta) - I had to reinstall 1.5.0 from the scratch.
And after fixing the unit of measurement from `m` to `km` - it's back to being normal. 

<img width="149" alt="Screenshot 2024-01-09 at 00 38 28" src="https://github.com/leeyuentuen/polestar_api/assets/1118933/a8c68070-a732-4e39-b225-c26ddef8d871">

**Comment by leeyuentuen** [comment] 2024-01-09 08:53
should fix here: https://github.com/leeyuentuen/polestar_api/releases/tag/1.5.1
also duplicate of #74

**Closed by leeyuentuen** 2024-01-09 08:53 UTC
